spec:
  inputs:
    sstate-mirror:
      type: boolean
      default: true
      description: Use shared sstate mirror
    downloads-mirror:
      type: boolean
      default: true
      description: Use shared downloads mirror
    deploy-public:
      type: boolean
      default: false
      description: Deploy to public HTTP server

---

include:
  - component: $CI_SERVER_FQDN/grinn/ci/ci-lib/deploy-public@deploy-public
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/workflow@1
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/build@1
    inputs:
      image-name: ghcr.io/siemens/kas/kas:5.1-debian-bookworm
      sstate-mirror: $[[ inputs.sstate-mirror ]]
      downloads-mirror: $[[ inputs.downloads-mirror ]]
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/lava@1

stages:
  - ci-kas
  - build
  - test
  - deploy

.ci_build_matrix: &ci_build_matrix
  parallel:
    matrix:
      - KAS_MACHINE:
        - grinn-astra-1680-ada
        - grinn-astra-1680-evb
        - grinn-astra-1680-sbc
        - grinn-astra-2619-sbc

.ci_test_matrix: &ci_test_matrix
  parallel:
    matrix:
      - KAS_MACHINE:
        - grinn-astra-1680-ada
        - grinn-astra-1680-evb
        - grinn-astra-1680-sbc

build:
  <<: *ci_build_matrix
  variables:
    KAS_TARGET: astra-media
  artifacts:
    expire_in: 1d
    paths:
      - build.log
      - build/tmp/deploy/images/*/*.rootfs.tar.xz
      - build/tmp/deploy/images/*/Image-*.bin
      - build/tmp/deploy/images/*/*.dtb
      - build/tmp/deploy/images/*/SYNAIMG

lava:
  <<: *ci_test_matrix
  needs:
    - lava-pre
    - job: build
      artifacts: true
      parallel:
        matrix:
          - KAS_MACHINE: ['$[[ matrix.KAS_MACHINE ]]']

deploy-public:
  <<: *ci_build_matrix
  variables:
    KAS_TARGET: astra-media
  rules:
    - if: $[[ inputs.deploy-public ]] == "true"
  needs:
    - job: build
      artifacts: true
      parallel:
        matrix:
          - KAS_MACHINE: ['$[[ matrix.KAS_MACHINE ]]']
  script:
    - apk add tar yq zstd
    - git clone --depth 1 --revision $CI_COMMIT_SHA $CI_REPOSITORY_URL

    - |
      DATE=${CI_PIPELINE_CREATED_AT%%T*}
      BRANCH=$(yq ".repos.meta-synaptics.branch" $CI_PROJECT_NAME/kas/default.yml)
      VERSION=${BRANCH##*_}
      COMMIT=${CI_COMMIT_SHA:0:10}
      FILE_NAME=$KAS_MACHINE-default-$DATE-$VERSION-$COMMIT.tar.zst

    - tar -cf - -C build/tmp/deploy/images/$KAS_MACHINE/ SYNAIMG/ | zstd -T0 -z -19 > $FILE_NAME
    - ci-lib/bin/deploy-public --upload-path astra/$DATE $FILE_NAME
