spec:
  inputs:
    sstate-mirror:
      type: boolean
      default: true
      description: Use shared sstate mirror
    downloads-mirror:
      type: boolean
      default: true
      description: Use shared downloads mirror
    git-mirror:
      type: boolean
      default: true
      description: Use git mirrors
    build-ref:
      default: ""
      description: Use specific pipeline id ("pipeline:12345") as build artifacts
    lava-test-definitions-revision:
      default: main
      description: Use specific git tag / branch / commit_id of lava-test-definitions (instead of default)

---

include:
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/deploy-public@3
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/workflow@3
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/build@3
    inputs:
      image-name: ghcr.io/siemens/kas/kas:5.2-debian-bookworm
      sstate-mirror: $[[ inputs.sstate-mirror ]]
      downloads-mirror: $[[ inputs.downloads-mirror ]]
      git-mirror: $[[ inputs.git-mirror ]]
      build-ref: $[[ inputs.build-ref ]]
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/lava@3
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/release-tag@3
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/lava@3
    inputs:
      lava-test-definitions-revision: $[[ inputs.lava-test-definitions-revision ]]

stages:
  - ci-kas
  - release-tag
  - build
  - test
  - deploy

.ci_build_matrix: &ci_build_matrix
  parallel:
    matrix:
      - KAS_MACHINE:
          - grinn-astra-1680-ada
          - grinn-astra-1680-sbc
          - grinn-astra-2619-sbc
        KAS_CONFIG:
          - default
      - KAS_MACHINE:
          - grinn-astra-1680-sbc
        KAS_CONFIG:
          - default:deepx

.ci_test_matrix: &ci_test_matrix
  parallel:
    matrix:
      - KAS_MACHINE:
          - grinn-astra-1680-ada
          - grinn-astra-1680-sbc
        KAS_CONFIG:
          - default
      - KAS_MACHINE:
          - grinn-astra-1680-sbc
        KAS_CONFIG:
          - default:deepx

.ci_build_artifacts: &ci_build_artifacts
  artifacts:
    expire_in: 4h
    paths:
      - build.env
      - build.log
      - build/tmp/deploy/images/*/*.rootfs.tar.zst
      - build/tmp/deploy/images/*/*.rootfs.synaimg.tar.zst
      - build/tmp/deploy/images/*/*.rootfs.synaimg.tar.zst.sha256sum
      - build/tmp/deploy/images/*/*.rootfs.synaimg_bootloader.tar.zst
      - build/tmp/deploy/images/*/Image-*.bin
      - build/tmp/deploy/images/*/*.dtb

build:
  <<: *ci_build_artifacts
  <<: *ci_build_matrix

build-download:
  <<: *ci_build_artifacts
  <<: *ci_build_matrix
  variables:
    JOB_NAME: "build: [$KAS_MACHINE, $KAS_CONFIG]"

lava-pre:
  <<: *ci_test_matrix

lava:
  <<: *ci_test_matrix
  needs:
    - job: lava-pre
      artifacts: true
      parallel:
        matrix:
          - KAS_MACHINE: ['$[[ matrix.KAS_MACHINE ]]']
            KAS_CONFIG: ['$[[ matrix.KAS_CONFIG ]]']
    - job: build
      artifacts: true
      optional: true
      parallel:
        matrix:
          - KAS_MACHINE: ['$[[ matrix.KAS_MACHINE ]]']
            KAS_CONFIG: ['$[[ matrix.KAS_CONFIG ]]']
    - job: build-download
      artifacts: true
      optional: true
      parallel:
        matrix:
          - KAS_MACHINE: ['$[[ matrix.KAS_MACHINE ]]']
            KAS_CONFIG: ['$[[ matrix.KAS_CONFIG ]]']

deploy-public:
  <<: *ci_build_matrix
  variables:
    DEPLOY_PUBLIC_FILE: build/tmp/deploy/images/$KAS_MACHINE/$KAS_TARGET-$KAS_MACHINE.rootfs.synaimg.tar.zst
  needs:
    - job: build
      artifacts: true
      parallel:
        matrix:
          - KAS_MACHINE: ['$[[ matrix.KAS_MACHINE ]]']
            KAS_CONFIG: ['$[[ matrix.KAS_CONFIG ]]']
