IMAGE_INSTALL:append:grinn-astra-1680-platform = " \
	image-sensor-demo \
	networkmanager-nmtui \
	terrasat-modem \
"

IMAGE_INSTALL:append:grinn-astra-1680-ada = " \
	hdmi-rx-demo \
"

IMAGE_INSTALL:append:grinn-astra-1680-evb = " \
	dmic-demo \
"

IMAGE_INSTALL:append:grinn-astra-1680-sbc = " \
	i2c-utils-optiga-trust \
"

IMAGE_INSTALL:append:grinn-astra-2619-platform = " \
	libgpiod \
	libgpiod-tools \
"
