header:
  version: 14

distro: poky
target: astra-media
machine: unset

local_conf_header:
  meta-grinn-astra: |
    DISTRO ?= "poky"
    PACKAGE_CLASSES ?= "package_deb"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    USER_CLASSES ?= "buildstats"
    PATCHRESOLVE = "noop"

    BB_DISKMON_DIRS ??= "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"

    CONF_VERSION = "2"
    LICENSE_FLAGS_ACCEPTED = "commercial Synaptics-EULA"
    DISTRO_FEATURES:remove = "3g nfc"
    SYNA_SDK_REVISION = ""
    INHERIT += "image-buildinfo"
    IMAGE_BUILDINFO_VARS:append = " SYNA_SDK_REVISION"

    INIT_MANAGER = "systemd"
    ROOT_HOME = "/home/root"

    INITRAMFS_IMAGE_BUNDLE = "1"
    INITRAMFS_IMAGE = "core-image-initramfs-boot"

    OPTEE_TA_ENC = "prod"

    PACKAGE_FEED_URIS ?= "https://astra-packages.synaptics.com/${ASTRA_VERSION}"
    EXTRA_IMAGE_FEATURES += " package-management "

    ENABLE_RESCUE_MODE = "0"

    IMAGE_CLASSES += "image_synaimg_tar image_synaimg_bootloader_tar"
    IMAGE_FSTYPES += "synaimg.tar.zst synaimg.tar.zst.sha256sum synaimg_bootloader.tar.zst tar.zst ext4.gz"

    GLIBC_GENERATE_LOCALES = "zh_CN.UTF-8 en_GB.UTF-8 en_US.UTF-8"
    IMAGE_LINGUAS = "zh-cn en-gb en-us"

    DISTRO_FEATURES:append = " wayland"
    DISTRO_FEATURES:append = " sysvinit"
    DISTRO_FEATURES:remove = " x11"
    DISTRO_FEATURES_NATIVESDK:remove = "x11"

    PREFERRED_VERSION_libgpiod = "1.6.4"

bblayers_conf_header:
  meta-grinn-astra: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

repos:
  poky:
    url: https://git.yoctoproject.org/poky
    commit: bab0f9f62af9af580744948dd3240f648a99879a
    branch: scarthgap
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded
    commit: b8d1a14f7f3b76457c36752202ea7ae5881b6654
    branch: scarthgap
    layers:
      meta-filesystems:
      meta-oe:
      meta-python:
      meta-multimedia:
      meta-networking:

  meta-browser:
    url: https://github.com/OSSystems/meta-browser
    commit: 0c43dd66e951624415516bdefcd7a7a8a641fbc3
    branch: scarthgap
    layers:
      meta-chromium:

  meta-clang:
    url: https://github.com/kraj/meta-clang
    commit: 9fbfa9db33131abdf3870a94f00199eb53e276e5
    branch: scarthgap

  meta-lts-mixins:
    url: https://github.com/jusst-engineering/meta-lts-mixins
    commit: 1793a1b8fc92cf8688c72b7fd4181e3a2f5ade55
    branch: scarthgap/rust

  meta-qt5:
    url: https://github.com/meta-qt5/meta-qt5
    commit: eb828418264a49b8d00035cb3d7b12fcea3be801
    branch: scarthgap

  meta-selinux:
    url: https://github.com/ni/meta-selinux
    commit: 30a49ab1298d2a081089a9e4c760a9e02f8100f6
    branch: nilrt/master/scarthgap

  meta-swupdate:
    url: https://github.com/sbabic/meta-swupdate
    commit: 4a65b1ed36c0b6ee4942d5f23c4984552b17cfe6
    branch: scarthgap

  meta-synaptics:
    url: https://github.com/synaptics-astra/meta-synaptics
    commit: a0344af9be13726ca196a9ed77e19cf77971e2e0
    branch: scarthgap_6.12_v2.3.0

  meta-grinn-astra:
    layers:
      meta-grinn-astra-bsp:
      meta-grinn-astra-fixes:
