#Main NetworkManager configuration
[main]
# Enables support for keyfile (modern NM connections)
plugins=keyfile

[logging]
#OFF, ERR, WARN, INFO, DEBUG
level=ERR

# NONE --> domain-specific logs.
# ALL  --> Logs everything.
# CORE --> Logs core NetworkManager operations.
# DEVICE --> Logs network devices (e.g., wlan0, eth0).
# WIRELESS --> Logs Wi-Fi events.
# SECURITY --> Logs authentication details (WPA, encryption failures).
# DHCP --> Logs DHCP client and server messages.
# IP4 / IP6 --> Logs IPv4 and IPv6 assignments.
# AUTOIP --> Logs auto-IP configurations.
# VPN --> Logs VPN-related events.
domains=ALL
