FILESEXTRAPATHS:prepend := "${THISDIR}/grinn-astra-2619-sbc:"

GRINN_SYNASDK_CONFIG_NATIVE_DEFCONFIG ?= ""

SRC_URI:append = "${@' file://' + d.getVar('GRINN_SYNASDK_CONFIG_NATIVE_DEFCONFIG') if d.getVar('GRINN_SYNASDK_CONFIG_NATIVE_DEFCONFIG') else ''}"

do_compile:prepend() {
	if [ -n "${GRINN_SYNASDK_CONFIG_NATIVE_DEFCONFIG}" ]; then
		cp ${WORKDIR}/${GRINN_SYNASDK_CONFIG_NATIVE_DEFCONFIG} \
			${S}/configs/product/${SYNA_SDK_CONFIG_NAME}/${SYNA_SDK_CONFIG_FILE}
	fi
}
