# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-grinn-astra-fixes"
BBFILE_PATTERN_meta-grinn-astra-fixes = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-grinn-astra-fixes = "10"

LAYERDEPENDS_meta-grinn-astra-fixes = "core"
LAYERSERIES_COMPAT_meta-grinn-astra-fixes = "scarthgap"

# Disable Synaptics tweaks for SWUpdate
BBMASK += "meta-synaptics/dynamic-layers/swupdate-layer/recipes-support/swupdate/swupdate_.*\.bbappend$"
